"""initial_schema

Revision ID: 6266ce2d1a8d
Revises: 
Create Date: 2026-05-28 20:22:05.920664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6266ce2d1a8d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan_tier', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('analytics_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('measurement_date', sa.Date(), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('controlled_substance_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('drug_name', sa.String(length=200), nullable=False),
    sa.Column('drug_schedule', sa.String(length=10), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('beginning_count', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('ending_count', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('expected_count', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('discrepancy', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('discrepancy_flag', sa.Boolean(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_time', sa.Time(), nullable=True),
    sa.Column('dispensed_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispensing_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=True),
    sa.Column('species', sa.String(length=50), nullable=True),
    sa.Column('client_id', sa.String(length=50), nullable=False),
    sa.Column('dispensing_vet_id', sa.String(length=50), nullable=False),
    sa.Column('drug_name', sa.String(length=200), nullable=False),
    sa.Column('ndc_code', sa.String(length=11), nullable=True),
    sa.Column('drug_schedule', sa.String(length=10), nullable=True),
    sa.Column('drug_category', sa.String(length=100), nullable=True),
    sa.Column('quantity_dispensed', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('days_supply', sa.Integer(), nullable=True),
    sa.Column('cost_of_goods', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('retail_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('filled_in_house', sa.Boolean(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('lot_number', sa.String(length=50), nullable=True),
    sa.Column('chronic_condition', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('drug_name', sa.String(length=200), nullable=False),
    sa.Column('ndc_code', sa.String(length=11), nullable=True),
    sa.Column('drug_schedule', sa.String(length=10), nullable=True),
    sa.Column('drug_category', sa.String(length=100), nullable=True),
    sa.Column('current_stock', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('reorder_point', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('retail_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('supplier', sa.String(length=100), nullable=True),
    sa.Column('last_ordered', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescription_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('prescription_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=True),
    sa.Column('species', sa.String(length=50), nullable=True),
    sa.Column('client_id', sa.String(length=50), nullable=False),
    sa.Column('prescribing_vet_id', sa.String(length=50), nullable=False),
    sa.Column('drug_name', sa.String(length=200), nullable=False),
    sa.Column('drug_category', sa.String(length=100), nullable=True),
    sa.Column('quantity_prescribed', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('retail_price_estimate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('date_written', sa.Date(), nullable=False),
    sa.Column('filled_in_house', sa.Boolean(), nullable=True),
    sa.Column('filled_date', sa.Date(), nullable=True),
    sa.Column('filled_pharmacy', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=32), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('prescription_records')
    op.drop_table('inventory_records')
    op.drop_table('dispensing_records')
    op.drop_table('controlled_substance_log')
    op.drop_table('analytics_results')
    op.drop_table('tenants')
    # ### end Alembic commands ###
