"""add_transaction_time_to_dispensing

Revision ID: cbc65e31d004
Revises: 6266ce2d1a8d
Create Date: 2026-05-28 20:23:00.974764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbc65e31d004'
down_revision: Union[str, None] = '6266ce2d1a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispensing_records', sa.Column('transaction_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dispensing_records', 'transaction_time')
    # ### end Alembic commands ###
